const soundfiles = {
    'chubby-chaser': { filename: 'chubby-chaser.mp3', label: 'Chubby Chaser' },
    'fabulous': { filename: 'fabulous.mp3', label: 'Fabulous' },
    'fierce': { filename: 'fierce.mp3', label: 'Fierce' },
    'gimme-some-sugar': { filename: 'gimme-some-sugar.mp3', label: 'Gimme Some Sugar' },
    'have-a-gay-day': { filename: 'have-a-gay-day.mp3', label: 'Have a Gay Day' },
    'he-gets-it-from-his-mother': { filename: 'he-gets-it-from-his-mother.mp3', label: 'He Gets It from His Mother' },
    'hes-terribly-butch': { filename: 'hes-terribly-butch.mp3', label: 'He\'s Terribly Butch' },
    'holler-at-you-later-homo': { filename: 'holler-at-you-later-homo.mp3', label: 'Holler at You Later Homo' },
    'homoriffic': { filename: 'homoriffic.mp3', label: 'Homoriffic' },
    'hug-me-bitch': { filename: 'hug-me-bitch.mp3', label: 'Hug Me Bitch' },
    'im-jealous-of-your-breasts': { filename: 'im-jealous-of-your-breasts.mp3', label: 'I\'m Jealous of Your Breasts' },
    'its-not-homophobia-sugar': { filename: 'its-not-homophobia-sugar.mp3', label: 'It\'s Not Homophobia Sugar' },
    'kisses': { filename: 'kisses.mp3', label: 'Kisses' },
    'lets-get-one-thing-straight': { filename: 'lets-get-one-thing-straight.mp3', label: 'Let\'s Get One Thing Straight' },
    'look-at-those-bitches': { filename: 'look-at-those-bitches.mp3', label: 'Look at Those Bitches' },
    'look-at-you-miss-thing': { filename: 'look-at-you-miss-thing.mp3', label: 'Look at You Miss Thing' },
    'oh-hey': { filename: 'oh-hey.mp3', label: 'Oh Hey' },
    'save-the-drama-for-your-momma': { filename: 'save-the-drama-for-your-momma.mp3', label: 'Save the Drama for Your Momma' },
    'that-was-amazing': { filename: 'that-was-amazing.mp3', label: 'That Was Amazing' },
    'this-old-thing': { filename: 'this-old-thing.mp3', label: 'This Old Thing' },
    'toodles': { filename: 'toodles.mp3', label: 'Toodles' },
    'what-happens-in-gaygas': { filename: 'what-happens-in-gaygas.mp3', label: 'What Happens in Gaygas' },
    'who-do-you-have-to-blow': { filename: 'who-do-you-have-to-blow.mp3', label: 'Who Do You Have to Blow' },
    'you-fag-hag': { filename: 'you-fag-hag.mp3', label: 'You Fag Hag' },
    'you-look-like-a-three-dollar-whore': { filename: 'you-look-like-a-three-dollar-whore.mp3', label: 'You Look Like a Three Dollar Whore' },
    'youre-a-hot-mess': { filename: 'youre-a-hot-mess.mp3', label: 'You\'re a Hot Mess' },
};

export default soundfiles